name: Conditional CI Test

on:
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test Command
        run: echo "Workflow triggered successfully!"
